site_name: Chiania
site_url: https://rudolfachter.github.io/chiania/public
#site_url: https://127.0.0.1:8000/blockchain-stuff/public
site_dir: public
copyright: |
  This site is community run and is not affiliated with the Chia Network.
  I am doing this in my free time as a hobby.<br/>
  Send coffee to: <strong>xch1wpdejgk86sh2mxwp3jrzrzftdh6et9en8cm9hzaw7xgf9h44p4usdjtypc</strong> (XCH | USDS | SMOON 🔜)<br/>
  You have a chiania item (NFT that you don't need anymore) for me? <br/>Send your mild gift to: <span style="color: #c5e1a5;">xch1t707p8usz9x3zx8ktdfcnuvqj709unclwqdxxshla0x3ytlkd58sucl8cf</span>
theme: 
  name: material
  custom_dir: theme
  logo: include/chiania-logo.gif
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - scheme: chiania_dark
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: chiania
      toggle:
        icon: material/weather-sunny
        name: Light Mode
  features:
      - toc.follow
      - toc.integrate
      - navigation.instant
      - navigation.tabs
      - navigation.expand
      - navigation.top
extra:
  tags:
    Linux: linux
    Chia: chia
    Bitcoin: bitcoin
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AchterRudolf
    - icon: fontawesome/brands/github
      link: https://github.com/RudolfAchter/chiania
    - icon: fontawesome/brands/mixcloud
      link: https://www.mixcloud.com/darul79/
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/rudolfachter
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/darul85


extra_css:
  - css/extra.css
  - https://unpkg.com/gridjs/dist/theme/mermaid.min.css

markdown_extensions:
  - toc
  - lightgallery
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - include/mermaid.min.js
  - include/jquery-3.6.0.min.js
  - include/extra.js
  

plugins:
  - search:
  - mkdocs-video:
      css_style:
        width: "1496px"
        height: "841px"
  - tags:
      tags_file: 00_tags.md
  - exclude:
      glob:
        - chia/chia_friends_puzzle/files/bafybeigzcazxeu7epmm4vtkuadrvysv74lbzzbl2evphtae6k57yhgynp4/*


